UCF101_LABELS = [
    'ApplyEyeMakeup', 'ApplyLipstick', 'Archery', 'BabyCrawling',
    'BalanceBeam', 'BandMarching', 'BaseballPitch', 'Basketball',
    'BasketballDunk', 'BenchPress', 'Biking', 'Billiards',
    'BlowDryHair', 'BlowingCandles', 'BodyWeightSquats', 'Bowling',
    'BoxingPunchingBag', 'BoxingSpeedBag', 'BreastStroke', 'BrushingTeeth',
    'CleanAndJerk', 'CliffDiving', 'CricketBowling', 'CricketShot',
    'CuttingInKitchen', 'Diving', 'Drumming', 'Fencing', 'FieldHockeyPenalty',
    'FloorGymnastics', 'FrisbeeCatch', 'FrontCrawl', 'GolfSwing',
    'Haircut', 'Hammering', 'HammerThrow', 'HandstandPushups',
    'HandstandWalking', 'HeadMassage', 'HighJump', 'HorseRace',
    'HorseRiding', 'HulaHoop', 'IceDancing', 'JavelinThrow',
    'JugglingBalls', 'JumpingJack', 'JumpRope', 'Kayaking',
    'Knitting', 'LongJump', 'Lunges', 'MilitaryParade',
    'Mixing', 'MoppingFloor', 'Nunchucks', 'ParallelBars',
    'PizzaTossing', 'PlayingCello', 'PlayingDaf', 'PlayingDhol',
    'PlayingFlute', 'PlayingGuitar', 'PlayingPiano', 'PlayingSitar',
    'PlayingTabla', 'PlayingViolin', 'PoleVault', 'PommelHorse',
    'PullUps', 'Punch', 'PushUps', 'Rafting', 'RockClimbingIndoor',
    'RopeClimbing', 'Rowing', 'SalsaSpin', 'ShavingBeard',
    'Shotput', 'SkateBoarding', 'Skiing', 'Skijet', 'SkyDiving',
    'SoccerJuggling', 'SoccerPenalty', 'StillRings', 'SumoWrestling',
    'Surfing', 'Swing', 'TableTennisShot', 'TaiChi', 'TennisSwing',
    'ThrowDiscus', 'TrampolineJumping', 'Typing', 'UnevenBars',
    'VolleyballSpiking', 'WalkingWithDog', 'WallPushups', 'WritingOnBoard',
    'YoYo'
]

HMDB51_LABELS = [
    "brush_hair",
    "cartwheel",
    "catch",
    "chew",
    "clap",
    "climb",
    "climb_stairs",
    "dive",
    "draw_sword",
    "dribble",
    "drink",
    "eat",
    "fall_floor",
    "fencing",
    "flic_flac",
    "golf",
    "handstand",
    "hit",
    "hug",
    "jump",
    "kick",
    "kick_ball",
    "kiss",
    "laugh",
    "pick",
    "pour",
    "pullup",
    "punch",
    "push",
    "pushup",
    "ride_bike",
    "ride_horse",
    "run",
    "shake_hands",
    "shoot_ball",
    "shoot_basket",
    "shoot_bow",
    "shoot_gun",
    "sit",
    "situp",
    "smile",
    "smoke",
    "somersault",
    "stand",
    "swing_baseball",
    "sword",
    "talk",
    "throw",
    "turn",
    "walk",
    "wave"
]
