VALID_KINETICS_ACTIONS = [
    "punching bag",
    "punching",
    "kicking",
    "hitting baseball",
    "wrestling",
    "tackling",
    "throwing axe",
    "throwing ball",
    "hammering",
    "whistling",

    "running",
    "jogging",
    "sprinting",
    "crawling",
    "climbing stairs",
    "climbing ladder",
    "climbing a rope",
    "climbing",
    "climbing tree",
    "parkour",
    "falling",
    "tripping",
    "jumping",

    "bending",
    "bending back",
    "bending metal",
    "getting up",
    "lying down",
    "sitting down",
    "standing",
    "leaning",

    "opening door",
    "closing door",
    "opening bottle",
    "opening present",
    "opening refrigerator",
    "opening wine bottle",
    "turning key",
    "using phone",
    "looking at phone",
    "using a screwdriver",
    "using a wrench",

    "carrying",
    "carrying baby",
    "dragging",
    "moving furniture",
]
